services:
  db:
    image: postgres:16
    container_name: weapon_store_db
    restart: always
    environment:
      POSTGRES_DB: weapon_store
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d weapon_store"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    container_name: weapon_store_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    env_file:
      - .env


volumes:
  postgres_data:
